# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc


export FRUIT="banana"
export PHRASE="$FRUIT $FRUIT"
alias f="echo $FRUIT"
echo $PHRASE

#Basic shell alias list:
alias c='clear'
alias ..='cd ..'
alias sa='ls -al'
alias cd+="cd I:\OSU"


#Git alias list:
alias g='git status'
alias gl='git log'
alias ga="git add ."
alias gc="git commit"
alias gp='git push'
alias gpom='git push origin master'
alias notepad="/c/Program\ Files\ \(x86\)/Notepad++/notepad++.exe"