# add ~/.bash_profile if needed for executing ~/.bashrc
echo "Hello"
echo $USER

###############
#	Exports	  #
###############

export PATH=$PATH:"C:\Program Files\Git\bin"
export PATH="$PATH:/usr/local/bin/"
export PATH="/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

######################
#	End of Exports   #
######################


##################
#	Set Colors	 #
##################
PS1="$PS1"'\[\033[32m\]'       # Changes promtp color to green

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
PS1="$PS1"'| Enter Command | '                  # prompt: always $
PS1="$PS1"'\[\033[33m\]'		   # Change to yellow


if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then
  printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n"
  echo "This looks like an incorrect setup."
  echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
fi

